"""Run TC-01…TC-08 against a fresh database and write docs/TEST_RESULTS.md (+ .json) and a sample PDF report.

    cd backend && python scripts/run_test_scenarios.py
"""
import json
import os
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT.parent / "docs"
os.environ.setdefault("DATABASE_URL", f"sqlite:///{Path(tempfile.mkdtemp()) / 'scenarios.db'}")
os.environ.setdefault("ENABLE_LIVE_WEATHER", "false")
sys.path.insert(0, str(ROOT))

from fastapi.testclient import TestClient  # noqa: E402

from app.main import app  # noqa: E402
from app.utils import clean  # noqa: E402
from tests.scenarios import ALL  # noqa: E402


def main():
    DOCS.mkdir(exist_ok=True)
    with TestClient(app) as c:
        recs = [clean(fn(c)) for fn in ALL]
        c.post("/api/pipeline/run-network", json={"trigger": "documentation"})
        rep = c.post("/api/reports/generate", json={"station_ids": ["ENV-ST-001", "ENV-ST-002", "ENV-ST-003", "ENV-ST-004", "ENV-WQ-001", "ENV-WQ-002", "ENV-NS-001", "ENV-NS-002"]}).json()
        c.post(f"/api/reports/{rep['id']}/approve", json={"actor": "Environmental Officer (demo)"})
        (DOCS / "sample_environmental_report.pdf").write_bytes(c.get(f"/api/reports/{rep['id']}/pdf").content)
    (DOCS / "TEST_RESULTS.json").write_text(json.dumps(recs, indent=2, ensure_ascii=False, default=str), encoding="utf-8")
    md = ["# Test Results — TC-01 to TC-08", "",
          "Generated by `backend/scripts/run_test_scenarios.py` against a fresh database (live weather disabled for determinism; "
          "the Weather Agent records its fallback source). The same scenario code runs in `pytest` (`tests/test_scenarios.py`).", "",
          "| Test | Scenario | Expected | Result |", "|---|---|---|---|"]
    md += [f"| {r['id']} | {r['scenario']} | {r['expected']} | {'✅ PASS' if r['passed'] else '❌ FAIL'} |" for r in recs]
    for r in recs:
        md += ["", f"## {r['id']} — {r['scenario']}", "",
               f"- **Input:** {r['input']}", f"- **Initial system state:** {r['initial_state']}", f"- **Expected output:** {r['expected']}",
               f"- **Actual output:** {r['actual']}", f"- **Agents involved:** {', '.join(dict.fromkeys(r['agents']))}",
               f"- **Pass/fail:** {'PASS' if r['passed'] else 'FAIL'}", "", "**Model / API output**", "", "```json",
               json.dumps(r["model_output"], indent=2, ensure_ascii=False, default=str), "```", "", "**Supporting evidence**", "", "```",
               json.dumps(r["evidence"], indent=2, ensure_ascii=False, default=str) if not isinstance(r["evidence"], str) else r["evidence"], "```"]
    (DOCS / "TEST_RESULTS.md").write_text("\n".join(md) + "\n", encoding="utf-8")
    print("\n".join(f"{r['id']}: {'PASS' if r['passed'] else 'FAIL'} — {r['actual'][:110]}" for r in recs))


if __name__ == "__main__":
    main()
